owner: diegograziano
repo: cuoteo-status
sites:
  - name: Cuoteo App
    url: https://cuoteo.app
  - name: Cuoteo API (Supabase)
    url: https://iguhrzdoneqcbkviqqwf.supabase.co
    expectedStatusCodes:
      - 404
status-website:
  baseUrl: /
  name: Cuoteo Status
  logoUrl: https://cuoteo.app/logo.png
