owner: diegograziano
repo: cuoteo-status
sites:
  - name: Cuoteo App
    url: https://cuoteo.app
  - name: Cuoteo API (Supabase)
    url: https://iguhrzdoneqcbkviqqwf.supabase.co/rest/v1/
status-website:
  baseUrl: /cuoteo-status
  name: Cuoteo Status
  logoUrl: https://cuoteo.app/logo.png
